version: '3'

services:
  db:
    image: postgres
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
