# Generated by Django 5.2.8 on 2025-11-22 07:52

import home.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 7),
                    ("rich_content", 8),
                    ("features", 11),
                    ("statistics", 13),
                    ("gallery", 16),
                    ("testimonials", 19),
                    ("programs", 22),
                    ("events", 24),
                    ("news", 26),
                    ("cta_button", 30),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 150}),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.FloatBlock", (), {"default": 0.45}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 60, "required": False},
                    ),
                    6: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("background_image", 2),
                                ("overlay_opacity", 3),
                                ("align", 4),
                                ("cta_primary_label", 5),
                                ("cta_primary_link", 6),
                                ("cta_secondary_label", 5),
                                ("cta_secondary_link", 6),
                            ]
                        ],
                        {},
                    ),
                    8: ("home.blocks.RichContentBlock", (), {}),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1), ("alignment", 4)]],
                        {"required": False},
                    ),
                    10: ("wagtail.blocks.ListBlock", (home.blocks.FeatureItem,), {}),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("section_header", 9), ("items", 10)]],
                        {},
                    ),
                    12: ("wagtail.blocks.ListBlock", (home.blocks.StatItem,), {}),
                    13: ("wagtail.blocks.StructBlock", [[("items", 12)]], {}),
                    14: ("wagtail.blocks.ListBlock", (2,), {}),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("grid", "Grid"),
                                ("masonry", "Masonry"),
                                ("carousel", "Carousel"),
                            ]
                        },
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [[("section_header", 9), ("images", 14), ("layout", 15)]],
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ListBlock",
                        (home.blocks.TestimonialItem,),
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("grid", "Grid"), ("slider", "Slider")]},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("section_header", 9), ("testimonials", 17), ("layout", 18)]],
                        {},
                    ),
                    20: ("wagtail.blocks.ListBlock", (home.blocks.ProgramItem,), {}),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("grid", "Grid"), ("cards", "Cards Horizontal")]},
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("section_header", 9), ("programs", 20), ("layout", 21)]],
                        {},
                    ),
                    23: ("wagtail.blocks.ListBlock", (home.blocks.EventItem,), {}),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("section_header", 9), ("events", 23)]],
                        {},
                    ),
                    25: ("wagtail.blocks.ListBlock", (home.blocks.NewsItem,), {}),
                    26: (
                        "wagtail.blocks.StructBlock",
                        [[("section_header", 9), ("news", 25)]],
                        {},
                    ),
                    27: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                    28: ("wagtail.blocks.URLBlock", (), {}),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("outline", "Outline"),
                            ]
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 27), ("link", 28), ("style", 29)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="page_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
