# Generated by Django 5.2.8 on 2025-11-22 08:08

import django.db.models.deletion
import home.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_content_homepage_page_title"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("page_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("section_header", 3),
                            ("rich_content", 4),
                            ("features", 7),
                            ("statistics", 9),
                            ("gallery", 13),
                            ("testimonials", 16),
                            ("programs", 19),
                            ("events", 21),
                            ("news", 23),
                            ("cta_button", 27),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 150}),
                            1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Left"),
                                        ("center", "Center"),
                                        ("right", "Right"),
                                    ]
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("subtitle", 1), ("alignment", 2)]],
                                {},
                            ),
                            4: ("home.blocks.RichContentBlock", (), {}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("subtitle", 1), ("alignment", 2)]],
                                {"required": False},
                            ),
                            6: (
                                "wagtail.blocks.ListBlock",
                                (home.blocks.FeatureItem,),
                                {},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("section_header", 5), ("items", 6)]],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.ListBlock",
                                (home.blocks.StatItem,),
                                {},
                            ),
                            9: ("wagtail.blocks.StructBlock", [[("items", 8)]], {}),
                            10: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            11: ("wagtail.blocks.ListBlock", (10,), {}),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("grid", "Grid"),
                                        ("masonry", "Masonry"),
                                        ("carousel", "Carousel"),
                                    ]
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("section_header", 5),
                                        ("images", 11),
                                        ("layout", 12),
                                    ]
                                ],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.ListBlock",
                                (home.blocks.TestimonialItem,),
                                {},
                            ),
                            15: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("grid", "Grid"), ("slider", "Slider")]},
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("section_header", 5),
                                        ("testimonials", 14),
                                        ("layout", 15),
                                    ]
                                ],
                                {},
                            ),
                            17: (
                                "wagtail.blocks.ListBlock",
                                (home.blocks.ProgramItem,),
                                {},
                            ),
                            18: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("grid", "Grid"),
                                        ("cards", "Cards Horizontal"),
                                    ]
                                },
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("section_header", 5),
                                        ("programs", 17),
                                        ("layout", 18),
                                    ]
                                ],
                                {},
                            ),
                            20: (
                                "wagtail.blocks.ListBlock",
                                (home.blocks.EventItem,),
                                {},
                            ),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [[("section_header", 5), ("events", 20)]],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.ListBlock",
                                (home.blocks.NewsItem,),
                                {},
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [[("section_header", 5), ("news", 22)]],
                                {},
                            ),
                            24: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                            25: ("wagtail.blocks.URLBlock", (), {}),
                            26: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ]
                                },
                            ),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 24), ("link", 25), ("style", 26)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
