# Generated by Django 5.2.8 on 2025-11-22 08:24

import home.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_aboutpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("hero", 7),
                    ("section_header", 8),
                    ("rich_content", 9),
                    ("statistics", 11),
                    ("gallery", 15),
                    ("testimonials", 18),
                    ("research", 20),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"max_length": 150}),
                    1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                    2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    3: ("wagtail.blocks.FloatBlock", (), {"default": 0.45}),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("left", "Left"),
                                ("center", "Center"),
                                ("right", "Right"),
                            ]
                        },
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 60, "required": False},
                    ),
                    6: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 1),
                                ("background_image", 2),
                                ("overlay_opacity", 3),
                                ("align", 4),
                                ("cta_primary_label", 5),
                                ("cta_primary_link", 6),
                                ("cta_secondary_label", 5),
                                ("cta_secondary_link", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1), ("alignment", 4)]],
                        {},
                    ),
                    9: ("home.blocks.RichContentBlock", (), {}),
                    10: ("wagtail.blocks.ListBlock", (home.blocks.StatItem,), {}),
                    11: ("wagtail.blocks.StructBlock", [[("items", 10)]], {}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1), ("alignment", 4)]],
                        {"required": False},
                    ),
                    13: ("wagtail.blocks.ListBlock", (2,), {}),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("grid", "Grid"),
                                ("masonry", "Masonry"),
                                ("carousel", "Carousel"),
                            ]
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("section_header", 12), ("images", 13), ("layout", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (home.blocks.TestimonialItem,),
                        {},
                    ),
                    17: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("grid", "Grid"), ("slider", "Slider")]},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("section_header", 12),
                                ("testimonials", 16),
                                ("layout", 17),
                            ]
                        ],
                        {},
                    ),
                    19: ("wagtail.blocks.ListBlock", (home.blocks.ResearchItem,), {}),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("section_header", 12), ("researches", 19)]],
                        {},
                    ),
                },
            ),
        ),
    ]
