# Generated by Django 5.2.8 on 2025-11-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_academicspage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="page_title",
        ),
        migrations.RemoveField(
            model_name="academicspage",
            name="page_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="page_title",
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="page_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicspage",
            name="page_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="page_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
