# Generated by Django 5.2.8 on 2025-11-22 08:38

import django.db.models.deletion
import home.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_aboutpage_page_title_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("page_description", models.TextField(blank=True, null=True)),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 7),
                            ("steps", 10),
                            ("rich_content", 11),
                            ("testimonials", 14),
                            ("cta_button", 18),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 150}),
                            1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.FloatBlock", (), {"default": 0.45}),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Left"),
                                        ("center", "Center"),
                                        ("right", "Right"),
                                    ]
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 60, "required": False},
                            ),
                            6: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("subtitle", 1),
                                        ("background_image", 2),
                                        ("overlay_opacity", 3),
                                        ("align", 4),
                                        ("cta_primary_label", 5),
                                        ("cta_primary_link", 6),
                                        ("cta_secondary_label", 5),
                                        ("cta_secondary_link", 6),
                                    ]
                                ],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("subtitle", 1), ("alignment", 4)]],
                                {"required": False},
                            ),
                            9: (
                                "wagtail.blocks.ListBlock",
                                (home.blocks.StepItem,),
                                {},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("section_header", 8), ("steps", 9)]],
                                {},
                            ),
                            11: ("home.blocks.RichContentBlock", (), {}),
                            12: (
                                "wagtail.blocks.ListBlock",
                                (home.blocks.TestimonialItem,),
                                {},
                            ),
                            13: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {"choices": [("grid", "Grid"), ("slider", "Slider")]},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("section_header", 8),
                                        ("testimonials", 12),
                                        ("layout", 13),
                                    ]
                                ],
                                {},
                            ),
                            15: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                            16: ("wagtail.blocks.URLBlock", (), {}),
                            17: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ]
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 15), ("link", 16), ("style", 17)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
