# Generated by Django 5.2.8 on 2025-11-22 09:05

import django.db.models.deletion
import home.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_researchpage"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("page_description", models.TextField(blank=True, null=True)),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 7),
                            ("contact_details", 11),
                            ("map", 13),
                            ("contact_form", 15),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 150}),
                            1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            2: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            3: ("wagtail.blocks.FloatBlock", (), {"default": 0.45}),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Left"),
                                        ("center", "Center"),
                                        ("right", "Right"),
                                    ]
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 60, "required": False},
                            ),
                            6: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("subtitle", 1),
                                        ("background_image", 2),
                                        ("overlay_opacity", 3),
                                        ("align", 4),
                                        ("cta_primary_label", 5),
                                        ("cta_primary_link", 6),
                                        ("cta_secondary_label", 5),
                                        ("cta_secondary_link", 6),
                                    ]
                                ],
                                {},
                            ),
                            8: ("wagtail.blocks.TextBlock", (), {}),
                            9: ("wagtail.blocks.CharBlock", (), {"max_length": 50}),
                            10: ("wagtail.blocks.EmailBlock", (), {}),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("address", 8),
                                        ("phone", 9),
                                        ("email", 10),
                                        ("office_hours", 1),
                                    ]
                                ],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Paste Google Maps iframe code."},
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("embed_code", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Your message has been sent."},
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("success_message", 14)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventsDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("page_description", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("location", models.CharField(blank=True, max_length=250)),
                ("body", wagtail.fields.RichTextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="EventsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("page_description", models.TextField(blank=True, null=True)),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("events_list", 5)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 150}),
                            1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Left"),
                                        ("center", "Center"),
                                        ("right", "Right"),
                                    ]
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("subtitle", 1), ("alignment", 2)]],
                                {"required": False},
                            ),
                            4: (
                                "wagtail.blocks.ListBlock",
                                (home.blocks.EventItem,),
                                {},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("section_header", 3), ("events", 4)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsDetailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("page_description", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("body", wagtail.fields.RichTextField()),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("page_description", models.TextField(blank=True, null=True)),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("news_list", 5)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 150}),
                            1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Left"),
                                        ("center", "Center"),
                                        ("right", "Right"),
                                    ]
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("subtitle", 1), ("alignment", 2)]],
                                {"required": False},
                            ),
                            4: (
                                "wagtail.blocks.ListBlock",
                                (home.blocks.NewsItem,),
                                {},
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [[("section_header", 3), ("news", 4)]],
                                {},
                            ),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
