# Generated by Django 3.2.25 on 2024-05-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N/A', 'N/A')], max_length=3)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('application_type', models.CharField(choices=[('Freshman', 'Freshman'), ('Transferee', 'Transferee'), ('Other', 'Other')], max_length=255)),
                ('admission_application', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Summer', 'Summer')], max_length=255)),
                ('name_of_last_high_school_attended', models.CharField(max_length=255)),
                ('year_graduated', models.DateField()),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('ranking_in_graduation_class', models.CharField(max_length=255)),
                ('lastest_gwa_percentile', models.CharField(max_length=255)),
                ('recognition', models.TextField(max_length=255)),
                ('high_school_organization', models.TextField(max_length=255)),
                ('Name_of_College_Last_Attended', models.TextField(max_length=255)),
                ('course_taken', models.TextField(max_length=255)),
                ('academic_year_last_attended', models.TextField(max_length=255)),
                ('college_achievement', models.TextField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
